### ISSUE TITLE
Multiplayer compatibility issue

### ISSUE THREAD

**Issue by Zediax** [Medacorp/Luigi-s-Mansion#101] opened 2023-11-28 19:48 UTC
**Describe the bug**
On Multiplayer Lunar Client, when the non-host player(s) tries to catch ghosts, their model don't move and loose the ghost.

**To Reproduce**
1. Go on the map with Lunar Client
2. Click on 'Host World'
3. Invite your friend(s)

**Expected behavior**
Non-host players models should be able to move and catch ghosts. 

**Map version:**
2.3.8

**Enabled add-ons**
None

**Additional context**
I don't know if it's because of LC or if it is an universal issue.

**Comment by Dhranios** [comment] 2023-11-28 19:56
Duplicate of #43

TLDR: not something I can fix as it's a Minecraft bug (https://bugs.mojang.com/browse/MC-197855)
Even lower frequency teleporting doesn't fix it as it depends on ping.

**Closed by Dhranios** 2023-11-28 19:56 UTC
Labels: Bug
